# more_20261004 / fewer_steps lane: oracle_fs_v1.py
# = the speed lane hook (verbatim copy infer_ll_hook_speed_v1_COPY.py, md5 7f5bf0becdd96e43a4a09075f35ad29d) with ONLY the
#   blocks marked "[oracle_fs_v1]" inserted; everything else is byte-identical to the copy (generated by insertion).
# ADDITION: the beyond_distil fine sub-integration substituted at chosen coarse steps of the CURRENT schedule (same
#   construction as skeptic1/oracle_mamba_v1.py and beyond_distil/oracle_infer.py: scheduler.step runs FIRST -- so the
#   step index, the per-step randn draw and the SK_RNG_PAD_TO pad draws are unchanged -- then prev_sample := x_target).
#   All of it is INERT unless OR_SUBST is set (O-C2 checks this by md5).
#   OR_SUBST   comma list of coarse step indices k of the current schedule to substitute
#   OR_M       comma list k:M -- substeps for that interval, Karras-uniform in sigma^(1/7) (bdlib.karras_substeps)
#   OR_PREFIX  k:p:sigma -- also record the state after p substeps of step k (asserted to sit at sigma, rel 1e-5)
#   OR_E2      k:sigma_mid -- diagnostic: the teacher's 2-coarse-step path sigma_k -> sigma_mid -> sigma_k+1 (1 extra call)
#   OR_CHECK   1 -> control at every substituted step of window 0: algebra (v0 given, M=1) vs scheduler prev_sample; the UNet
#              re-run through the fine-step input path (with and without autocast) vs the pipeline's own model_output.
# bdlib (scripts/distill/runs/beyond_distil/bdlib.py, UNCHANGED) supplies all the algebra; for CFG batch 2 without a prefix
#   capture bdlib.fine_step itself is called.  The ONLY new code path is the batch-1 branch (guidance exactly 1.0, the pipeline
#   then runs without CFG and frame/mask/emb/add have batch 1).  Diagnostics -> <SK_OUT>/oracle_diag.json.
#!/usr/bin/env python
"""finalcheck_20261004 / speed lane: COPY of scripts/distill/runs/skeptic1/infer_ll_hook.py
(the copy as taken is kept next to this file as infer_ll_hook_ORIG_COPY.py).

The deployed-inference path (config, ii.run kwargs, FFV1 writer imported by path from
scripts/distill/runs/fulldata_v2/beyond4/infer_lossless.py, optional 15-tensor swap) is UNCHANGED.
Additions, each INERT unless its env knob is set:

  SK_SIGMAS      comma-separated sigma list ENDING AT sigma_min (e.g. the T5 schedule
                 "700.0,7.276163101196289,1.1675708293914795,0.09738767892122269,0.0020000000949949026").
                 Installed by wrapping EulerDiscreteScheduler.set_timesteps at CLASS level (so main()'s own
                 startup "[sched][inference][timesteps_head]" print shows the custom schedule too).
                 The wrapper drops the pipeline's num_inference_steps and calls the ORIGINAL set_timesteps
                 with sigmas=<list>+[0.0]: the installed diffusers 0.29.2 natively accepts sigmas= but does
                 NOT append the trailing 0 itself (it uses the list as given and sets
                 num_inference_steps = len(sigmas)-1). Natively it then sets
                 timesteps = 0.25*ln(sigma) (timestep_type continuous + v_prediction), num_inference_steps,
                 and resets _step_index/_begin_index -- exactly the EulerDiscreteScheduler code path.
                 Every kept sigma AND its timestep is asserted bit-equal to an entry of the scheduler's own
                 default 8-step schedule computed on the same device.
                 SK_STEPS is ignored when SK_SIGMAS is set (steps = len(list)).
  SK_RNG_PAD_TO  integer M: after the LAST scheduler step of every window, draw (M - N) discarded
                 randn_tensor(model_output.shape, dtype=model_output.dtype, device=model_output.device)
                 samples -- the identical call EulerDiscreteScheduler.step() makes on every step even at
                 gamma=0 (its noise is unused when s_churn=0). An N-step schedule then consumes the global
                 CUDA RNG exactly like the deployed 8-step schedule, so every window starts from the SAME
                 initial noise as the deployed render (paired comparison). A MEASUREMENT DEVICE only:
                 a shipped N-step sampler would run unpadded.
  SK_GUID        min = max guidance (default 1.01, as before; the driver now lets it be inherited).

Passive instrumentation (the c1/c2 md5 controls run WITH it installed, so any perturbation would show):
  per window: CUDA-synchronised wall seconds of the pipeline __call__ (CLIP+VAE encode + sampling loop,
  output_type="latent" so no decode inside), UNet call count + batch sizes (forward pre-hook), UNet GPU ms
  (CUDA events around each forward), md5 of the raw bits of the initial latents returned by
  prepare_latents (the RNG-pairing fingerprint); process: import->first call (model load), total.
  -> <SK_OUT>/speed_log.json and one "[speed]" summary line.
"""
import importlib.util, os, sys, collections, time, json, hashlib

T_IMPORT = time.time()
REPO = "/home/kawa/master_project/StereoCrafter"
sys.path.insert(0, REPO)
os.chdir(REPO)

# import the beyond4 lossless wrapper by path (applies II.write_video_opencv = FFV1 writer)
_spec = importlib.util.spec_from_file_location(
    "infer_lossless", f"{REPO}/scripts/distill/runs/fulldata_v2/beyond4/infer_lossless.py")
_IL = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_IL)

import torch
import inpainting_inference as ii
# ---- [oracle_fs_v1] bdlib (UNCHANGED) for the fine sub-integration algebra
import math
sys.path.insert(0, f"{REPO}/scripts/distill/runs/beyond_distil")
import bdlib as B
from diffusers.schedulers.scheduling_euler_discrete import EulerDiscreteScheduler as _ES
from diffusers.utils.torch_utils import randn_tensor

CLIP = os.environ["SK_CLIP"]
OUT = os.environ["SK_OUT"]
STEPS = int(os.environ.get("SK_STEPS", "8"))
GUID = float(os.environ.get("SK_GUID", "1.01"))
UNET = os.environ.get("SK_UNET", "").strip() or None
CK = os.environ.get("SK_CK", "").strip()
SIG = [float(x) for x in os.environ.get("SK_SIGMAS", "").split(",") if x.strip()]
PAD_TO = os.environ.get("SK_RNG_PAD_TO", "").strip()
PAD_TO = int(PAD_TO) if PAD_TO else None

assert ii.write_video_opencv is _IL._patched_write, "lossless writer patch did not take"

# ------------------------------------------------------------------ custom sigma schedule (SK_SIGMAS)
_orig_set = _ES.set_timesteps
_orig_step = _ES.step
_REF = {}          # device-string -> (sigmas, timesteps) of the default 8-step schedule
SCHED_LOG = {}

if SIG:
    assert all(SIG[i] > SIG[i + 1] for i in range(len(SIG) - 1)), f"SK_SIGMAS must strictly decrease: {SIG}"
    assert SIG[-1] > 0.0, "SK_SIGMAS must END at sigma_min; the trailing 0 is appended here"
    STEPS = len(SIG)

    def _ref_for(self, device):
        key = str(device)
        if key not in _REF:
            ref = _ES.from_config(self.config)
            _orig_set(ref, 8, device=device)
            _REF[key] = (ref.sigmas.clone(), ref.timesteps.detach().clone().cpu())
        return _REF[key]

    def _set_custom(self, num_inference_steps=None, device=None, timesteps=None, sigmas=None):
        assert timesteps is None and sigmas is None, "custom-sigma wrapper got timesteps/sigmas from caller"
        ref_sig, ref_ts = _ref_for(self, device)
        _orig_set(self, None, device=device, sigmas=list(SIG) + [0.0])
        # ---- checks: exact schedule, exact kept points, reset indices
        assert self.num_inference_steps == len(SIG), self.num_inference_steps
        assert len(self.timesteps) == len(SIG) and len(self.sigmas) == len(SIG) + 1
        assert float(self.sigmas[-1]) == 0.0
        assert self._step_index is None and self._begin_index is None
        ts_cpu = self.timesteps.detach().cpu()
        idx = []
        for k in range(len(SIG)):
            hit = (ref_sig[:-1] == self.sigmas[k]).nonzero().flatten().tolist()
            assert len(hit) == 1, f"sigma {float(self.sigmas[k])!r} is not an exact default-8 sigma"
            j = hit[0]
            assert torch.equal(ts_cpu[k], ref_ts[j]), (k, j, float(ts_cpu[k]), float(ref_ts[j]))
            idx.append(j)
        key = str(device)
        if key not in SCHED_LOG:
            SCHED_LOG[key] = dict(sigmas=[repr(float(s)) for s in self.sigmas],
                                  timesteps=[repr(float(t)) for t in ts_cpu],
                                  default8_index=idx, num_inference_steps=int(self.num_inference_steps))
            print(f"[speed] custom schedule on {key}: sigmas={SCHED_LOG[key]['sigmas']} "
                  f"timesteps={SCHED_LOG[key]['timesteps']} default8_index={idx} "
                  f"(all kept sigma+timestep bit-equal to the default 8-step entries)", flush=True)

    _ES.set_timesteps = _set_custom

# ------------------------------------------------------------------ RNG pad (SK_RNG_PAD_TO)
STATS = dict(pad_draws=0, windows=[])
CUR = {}

if PAD_TO is not None:
    def _step_pad(self, model_output, timestep, sample, *a, **k):
        out = _orig_step(self, model_output, timestep, sample, *a, **k)
        if self._step_index == len(self.timesteps):          # the window's last step just ran
            K = PAD_TO - len(self.timesteps)
            assert K >= 0, f"SK_RNG_PAD_TO={PAD_TO} < steps {len(self.timesteps)}"
            for _ in range(K):
                randn_tensor(model_output.shape, dtype=model_output.dtype, device=model_output.device,
                             generator=k.get("generator"))
            STATS["pad_draws"] += K
            if CUR:
                CUR["pad_draws"] = K
        return out

    _ES.step = _step_pad

print(f"[sk] clip={CLIP} steps={STEPS} guid={GUID} unet={UNET} ck={CK or None} out={OUT} "
      f"sigmas={SIG or None} rng_pad_to={PAD_TO}", flush=True)

SWAP = {}
if CK:
    raw = torch.load(CK, map_location="cpu", weights_only=False)
    SWAP = raw.get("model", raw)
    print(f"[sk] distilled ckpt: {len(SWAP)} tensors", flush=True)

# ------------------------------------------------------------------ passive instrumentation
_orig_prep = ii._Pipe.prepare_latents


def _prep_fp(self, *a, **k):
    lat = _orig_prep(self, *a, **k)
    with torch.no_grad():
        raw_bits = lat.detach().contiguous().view(torch.int16) if lat.element_size() == 2 else lat.detach().contiguous()
        CUR["init_md5"] = hashlib.md5(raw_bits.cpu().numpy().tobytes()).hexdigest()
        CUR["init_shape"] = list(lat.shape)
        CUR["init_dtype"] = str(lat.dtype)
    return lat


ii._Pipe.prepare_latents = _prep_fp


def _unet_pre(mod, args, kwargs):
    sample = args[0] if args else kwargs["sample"]
    CUR.setdefault("batches", []).append(int(sample.shape[0]))
    ev = torch.cuda.Event(enable_timing=True)
    ev.record()
    CUR.setdefault("ev", []).append([ev, None])


def _unet_post(mod, args, kwargs, output):
    ev = torch.cuda.Event(enable_timing=True)
    ev.record()
    CUR["ev"][-1][1] = ev


# ------------------------------------------------------------------ [oracle_fs_v1] fine sub-integration substitution
OR_SUBST = sorted({int(x) for x in os.environ.get("OR_SUBST", "").split(",") if x.strip()})
OR_M = {int(a.split(":")[0]): int(a.split(":")[1]) for a in os.environ.get("OR_M", "").split(",") if a.strip()}
OR_PREFIX = {}
for _a in os.environ.get("OR_PREFIX", "").split(","):
    if _a.strip():
        _k, _p, _s = _a.split(":")
        OR_PREFIX[int(_k)] = (int(_p), float(_s))
OR_E2 = {int(a.split(":")[0]): float(a.split(":")[1]) for a in os.environ.get("OR_E2", "").split(",") if a.strip()}
OR_CHECK = os.environ.get("OR_CHECK", "").strip() == "1"
for _k in OR_SUBST:
    assert _k in OR_M, f"OR_M must give M for every substituted step; missing {_k}"
ORC = dict(win=None)
ORC_OUT = dict(subst=OR_SUBST, M=OR_M, prefix={k: list(v) for k, v in OR_PREFIX.items()}, e2=OR_E2, check=OR_CHECK,
               guid=GUID, unet_state=UNET, windows=[], controls=[], usage={})
print(f"[oracle] subst={OR_SUBST} M={OR_M} prefix={OR_PREFIX} e2={OR_E2} check={OR_CHECK}", flush=True)


def _rel(a, b):
    """||a - b|| / ||b||"""
    a = a.float()
    b = b.float().to(a.device)
    return float((a - b).norm() / b.norm())


@torch.no_grad()
def _unet_v(unet, xx, s, frame_lat, mask_lat, emb, add, guid, dt, autocast=True):
    """The UNet velocity at (xx, s) through bdlib.fine_step's input path.  Batch 2 = CFG exactly as bdlib; batch 1 = the
    pipeline without CFG (guidance exactly 1.0)."""
    dev = frame_lat.device
    xs = (xx.float() / math.sqrt(s * s + 1.0)).to(dev, dt)
    if frame_lat.shape[0] == 2:
        inp = torch.cat([xs.repeat(2, *([1] * (xs.dim() - 1))), frame_lat, mask_lat], dim=2)
    else:
        assert frame_lat.shape[0] == 1 and guid == 1.0, (tuple(frame_lat.shape), guid)
        inp = torch.cat([xs, frame_lat, mask_lat], dim=2)
    tt = torch.tensor([B.t_of_sigma(s)], dtype=torch.float32, device=dev)
    if autocast:
        with torch.autocast(device_type="cuda", dtype=dt):
            v = unet(inp, tt, encoder_hidden_states=emb, added_time_ids=add, return_dict=False)[0]
    else:
        v = unet(inp, tt, encoder_hidden_states=emb, added_time_ids=add, return_dict=False)[0]
    v = v.float()
    if v.shape[0] == 2:
        return v[0:1] + guid * (v[1:2] - v[0:1])
    return v


@torch.no_grad()
def _fine(unet, x, sg, sg1, m, fr, mk, emb, add, guid, v0, dt, keep=()):
    """bdlib.fine_step's loop (same substeps, same algebra) + a batch-1 branch + optional capture of the state after
    substep p (p in keep).  CFG batch 2 without capture CALLS bdlib.fine_step itself (the established path)."""
    subs = B.karras_substeps(sg, sg1, m)
    if fr.shape[0] == 2 and not keep:
        return B.fine_step(unet, x, sg, sg1, m, fr, mk, emb, add, guid=guid, v0=v0, dt=dt), {}, subs
    xx = x.float()
    states = {}
    for j in range(m):
        s, s1 = subs[j], subs[j + 1]
        if j == 0 and v0 is not None:
            vcfg = v0.float()
        else:
            vcfg = _unet_v(unet, xx, s, fr, mk, emb, add, guid, dt)
        x0h = B.x0hat_from_v(vcfg, xx.to(vcfg.device), s)
        xx = B.euler_next(xx.to(vcfg.device), x0h, s, s1)
        if (j + 1) in keep:
            states[j + 1] = (s1, xx.clone())
    return xx, states, subs


def _install_oracle(pipe):
    unet = pipe.unet
    sch = pipe.scheduler
    stash = {}
    _fwd = unet.forward

    def fwd(sample, timestep, *fa, **fk):
        stash["frame"] = sample[:, :, 4:8]
        stash["mask"] = sample[:, :, 8:9]
        stash["emb"] = fk.get("encoder_hidden_states", fa[0] if fa else None)
        stash["add"] = fk.get("added_time_ids", None)
        return _fwd(sample, timestep, *fa, **fk)

    _step = sch.step          # the class-level step (incl. the SK_RNG_PAD_TO pad when set), bound to this scheduler

    def step(model_output, timestep, sample, **kw):
        kk = sch.step_index if sch.step_index is not None else 0
        sg = float(sch.sigmas[kk])
        sg1 = float(sch.sigmas[kk + 1])
        out = _step(model_output, timestep, sample, **kw)       # advances step_index, consumes the RNG draw(s)
        u = ORC_OUT["usage"]
        if kk not in OR_SUBST:
            u[f"{kk}_coarse"] = u.get(f"{kk}_coarse", 0) + 1
            return out
        win = ORC["win"]
        dt = model_output.dtype
        fr, mk, emb, add = stash["frame"], stash["mask"], stash["emb"], stash["add"]
        y = sample.float()
        v0 = model_output.float()
        x0o = B.x0hat_from_v(v0, y, sg)
        rec = dict(win=win, k=kk, sigma=sg, sigma_next=sg1, M=OR_M[kk], batch=int(fr.shape[0]))
        if OR_CHECK and win == 0:
            xa = B.euler_next(y, x0o, sg, sg1)
            vb = _unet_v(unet, y, sg, fr, mk, emb, add, GUID, dt, autocast=True)
            vc = _unet_v(unet, y, sg, fr, mk, emb, add, GUID, dt, autocast=False)
            xb = B.euler_next(y, B.x0hat_from_v(vb, y, sg), sg, sg1)
            ctl = dict(win=win, k=kk, sigma=sg, batch=int(fr.shape[0]),
                       rel_x_alg_M1_vs_sched=_rel(xa, out.prev_sample),
                       rel_v_recompute_autocast=_rel(vb, v0), rel_v_recompute_noautocast=_rel(vc, v0),
                       rel_x_M1_recompute_vs_sched=_rel(xb, out.prev_sample),
                       rel_x0_alg_vs_sched_pred_original=_rel(x0o, out.pred_original_sample))
            ORC_OUT["controls"].append(ctl)
            print(f"[oracle] CONTROL {ctl}", flush=True)
        keep = (OR_PREFIX[kk][0],) if kk in OR_PREFIX else ()
        xt, states, subs = _fine(unet, y, sg, sg1, OR_M[kk], fr, mk, emb, add, GUID, v0, dt, keep=keep)
        x0t = B.x0hat_target_from_xtarget(xt, y, sg, sg1)
        rec.update(subs=[float(s) for s in subs],
                   dx0=_rel(x0t, x0o), tgterr=_rel(x0o, x0t), trunc=_rel(B.euler_next(y, x0o, sg, sg1), xt))
        if kk in OR_PREFIX:
            p, sexp = OR_PREFIX[kk]
            sp, xp = states[p]
            assert abs(sp - sexp) / sexp < 1e-5, (sp, sexp)
            x0tp = B.x0hat_target_from_xtarget(xp, y, sg, sp)
            rec.update(prefix_p=p, prefix_sigma=sp, dx0_prefix=_rel(x0tp, x0o), tgterr_prefix=_rel(x0o, x0tp),
                       trunc_prefix=_rel(B.euler_next(y, x0o, sg, sp), xp))
        if kk in OR_E2:
            smid = OR_E2[kk]
            xm = B.euler_next(y, x0o, sg, smid)
            vm = _unet_v(unet, xm, smid, fr, mk, emb, add, GUID, dt)
            x2 = B.euler_next(xm, B.x0hat_from_v(vm, xm, smid), smid, sg1)
            x1 = B.euler_next(y, x0o, sg, sg1)
            rec.update(e2_mid=smid, end_err_1coarse=_rel(x1, xt), end_err_2coarse=_rel(x2, xt))
        ORC_OUT["windows"].append(rec)
        u[f"{kk}_fine"] = u.get(f"{kk}_fine", 0) + 1
        out.prev_sample = xt.to(model_output.dtype)
        return out

    unet.forward = fwd
    sch.step = step
    unet._or_installed = True
    print("[oracle] installed on unet.forward + scheduler.step", flush=True)


T_FIRST_CALL = None
_call = ii._Pipe.__call__


def wrapped_call(self, *a, **k):
    global T_FIRST_CALL
    if T_FIRST_CALL is None:
        T_FIRST_CALL = time.time()
    unet = self.unet
    if SWAP and not getattr(unet, "_sk_installed", False):
        params = dict(unet.named_parameters())
        # the Mamba adapter re-parents the original attention as `<...>.attn1.origin_attn.*`
        mapping, missing = {}, []
        for key in SWAP:
            if key in params:
                mapping[key] = key
            else:
                alt = key.replace(".attn1.", ".attn1.origin_attn.")
                if alt in params:
                    mapping[key] = alt
                else:
                    missing.append(key)
        nplain = sum(1 for kk, vv in mapping.items() if kk == vv)
        nremap = len(mapping) - nplain
        print(f"[sk] swap mapping: {nplain} direct, {nremap} remapped to origin_attn.*, "
              f"{len(missing)} NOT FOUND", flush=True)
        if missing:
            print(f"[sk] missing keys: {missing[:3]} ...", flush=True)
        ndiff = 0
        with torch.no_grad():
            for kk, pk in mapping.items():
                p = params[pk]
                v = SWAP[kk].to(device=p.device, dtype=p.dtype)
                ndiff += int((v != p).any())
                p.copy_(v)
        print(f"[sk] tensors that differed from the loaded model: {ndiff}/{len(mapping)}", flush=True)
        # report whether the modules we just wrote to are even evaluated
        from blocks.mamba_diffusers_adapter import GatedResidualMambaSelfAttention as G
        gated = [(n, float(m.mamba_gate), bool(m.reference_disabled))
                 for n, m in unet.named_modules() if isinstance(m, G)]
        for n, g, rd in gated:
            print(f"[sk] gated module {n}: gate={g} reference_disabled={rd} "
                  f"origin_attn_evaluated={not (rd or g >= 1.0)}", flush=True)
        unet._sk_installed = True
    # ---- [oracle_fs_v1] install once; record the index of the window about to run
    if OR_SUBST and not getattr(unet, "_or_installed", False):
        _install_oracle(self)
    ORC["win"] = len(STATS["windows"])
    if not getattr(unet, "_speed_hooks", False):
        unet.register_forward_pre_hook(_unet_pre, with_kwargs=True)
        unet.register_forward_hook(_unet_post, with_kwargs=True)
        unet._speed_hooks = True
    CUR.clear()
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    out = _call(self, *a, **k)
    torch.cuda.synchronize()
    t1 = time.perf_counter()
    evs = CUR.pop("ev", [])
    rec = dict(call_s=t1 - t0,
               unet_calls=len(evs),
               batches=CUR.get("batches", []),
               unet_ms=sum(s.elapsed_time(e) for s, e in evs),
               init_md5=CUR.get("init_md5"),
               init_shape=CUR.get("init_shape"),
               init_dtype=CUR.get("init_dtype"),
               pad_draws=CUR.get("pad_draws", 0),
               num_frames=k.get("num_frames"))
    STATS["windows"].append(rec)
    return out


ii._Pipe.__call__ = wrapped_call

kw = dict(config="config/0160_overfit_inference_matched.json",
          input_video_path=f"video_data/splatting/{CLIP}_splatting_results.mp4",
          save_dir=OUT, num_inference_steps=STEPS,
          min_guidance_scale=GUID, max_guidance_scale=GUID)
if UNET is None:
    kw["unet_state_path"] = None
else:
    kw["unet_state_path"] = UNET
    kw["expected_partial_unet_state"] = True
    kw["mamba_gate_override"] = 1.0
ii.run(**kw)
T_END = time.time()

W = STATS["windows"]
summary = dict(clip=CLIP, out=OUT, guid=GUID, steps=STEPS, sigmas=SIG or None, rng_pad_to=PAD_TO,
               unet_state=UNET, ck=CK or None,
               n_windows=len(W),
               unet_calls_total=sum(w["unet_calls"] for w in W),
               unet_calls_per_window=sorted(set(w["unet_calls"] for w in W)),
               batch_sizes=sorted(set(b for w in W for b in w["batches"])),
               call_s_sum=sum(w["call_s"] for w in W),
               unet_ms_sum=sum(w["unet_ms"] for w in W),
               pad_draws_total=STATS["pad_draws"],
               load_s=(T_FIRST_CALL - T_IMPORT) if T_FIRST_CALL else None,
               hook_total_s=T_END - T_IMPORT,
               schedule=SCHED_LOG or None,
               init_md5=[w["init_md5"] for w in W],
               windows=W)
# ---- [oracle_fs_v1] diagnostics
if OR_SUBST:
    _summ = {}
    for _k in OR_SUBST:
        _rs = [r for r in ORC_OUT["windows"] if r["k"] == _k]
        _summ[str(_k)] = dict(n=len(_rs))
        for _key in ("dx0", "tgterr", "trunc", "dx0_prefix", "tgterr_prefix", "trunc_prefix",
                     "end_err_1coarse", "end_err_2coarse"):
            _v = [r[_key] for r in _rs if _key in r]
            if _v:
                _summ[str(_k)][_key] = sum(_v) / len(_v)
    ORC_OUT["summary"] = _summ
    with open(os.path.join(OUT, "oracle_diag.json"), "w") as fh:
        json.dump(ORC_OUT, fh, indent=1)
    print(f"[oracle] usage={ORC_OUT['usage']} summary={_summ}", flush=True)
with open(os.path.join(OUT, "speed_log.json"), "w") as fh:
    json.dump(summary, fh, indent=1)
print(f"[speed] windows={summary['n_windows']} unet_calls={summary['unet_calls_total']} "
      f"per_window={summary['unet_calls_per_window']} batch={summary['batch_sizes']} "
      f"call_s_sum={summary['call_s_sum']:.2f} unet_s_sum={summary['unet_ms_sum'] / 1000:.2f} "
      f"load_s={summary['load_s']:.1f} hook_total_s={summary['hook_total_s']:.1f} "
      f"pad_draws={summary['pad_draws_total']} "
      f"init_md5_all={hashlib.md5(''.join(summary['init_md5']).encode()).hexdigest()}", flush=True)
print("[sk] done", flush=True)
